library(splitstackshape)
library(PanelMatch)
library(rgdal)
library(stringdist)
library(wru)
library(kableExtra)
library(sqldf)
library(Metrics)
library(RSQLite)
library(ebal)
library(fixest)
library(modelsummary)
options("modelsummary_format_numeric_latex" = "plain")
library(tidycensus)
library(multcomp)
library(miceadds)
library(Matching)
library(plm)
library(readstata13)
library(lubridate)
library(ggeffects)
library(scales)
library(extrafont)
library(data.table)
library(stargazer)
library(psych)
library(tidyverse)
library(BrennanTools)

save <- c("db", "cleanup", "theme_bc", "save", "weighted.ttest.ci")


cleanup <- function(...){
  save2 <- c(save, ...)
  rm(list=ls(envir = .GlobalEnv)[! ls(envir = .GlobalEnv) %in% save2], envir = .GlobalEnv)
}
