---
title: "Grief and Anger: Disentangling the Effects of COVID-19 on Turnout"
subtitle: ""
thanks: Thanks.
author: Kevin Morris^[Researcher, Brennan Center for Justice at NYU School of Law, 120 Broadway Ste 1750, New York, NY 10271 (kevin.morris@nyu.edu)]
institute: "Brennan Center for Justice"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
    latex_engine: xelatex
    keep_tex: true
bibliography: "wa_covid.bib"
link-citations: yes
fontsize: 12pt
header-includes:
 - \usepackage{rotating}
 - \usepackage{setspace}
 - \usepackage{lineno}
 # - \linenumbers
abstract: |
 The novel coronavirus SARS-CoV-2 (COVID-19) has upended normal routines across the United States. Nearly 600 thousand Americans have died of COVID-19, and more than 33 million have tested positive for the illness. At the same time, there is widespread perception that the government’s response to the pandemic has been lackluster, and the racial disparities are clear. This manuscript tests whether COVID mobilized nonwhite voters to participate on the basis of political threat, or was simply a discouraging event. By leveraging individual-level death records from Washington State, I identify registered voters who lived with individuals who died from COVID- 19, testing whether this was a mobilizing effect, especially for non-white voters. These analyses are supplemented with survey data exploring whether COVID-19 was differ- ently mobilizing for voters depending on how close they feel to their racial or ethnic group.
---
\pagenumbering{gobble}
\pagebreak
```{r setup, echo = F, message = F, warning = F}
knitr::opts_knit$set(root.dir = "..", dev = "cairo_pdf")
library(systemfit)
library(kevostools)
library(AER)
library(sandwich)
library(lmtest)
library(scales)
library(ggpubr)
library(tidyverse)
library(extrafont)
library(kableExtra)
library(data.table)
library(stargazer)
loadfonts()
```
\pagenumbering{arabic}
\doublespacing

## Introduction {-}

Introduction
On January 21, 2020, the first case of SARS-CoV-2 (or "COVID-19") was confirmed in the state of Washington [@McNerthney2020]. President Donald Trump made his first public comments on the new virus the next day from Davos, telling CNBC "we have it totally under control. It's one person coming in from China, and we have it under control" [@Calia2020]. A few days later, on January 30, he said at a manufacturing plant in Michigan that "we think we have it very well under control," assuring listeners that "it's going to have a very good ending for it" [@whitehouse2020]. Meanwhile, cases were identified in states across the country. The first confirmed death attributed to COVID-19 occurred in Northern California on February 4th [@Moon2020]. By early March, Washington State was being called the center of the outbreak in the United States [@Golden2020], although New York City would soon claim that dubious honor. By the time of the 2020 presidential election, more than 8.3 million Americans had tested positive for the novel coronavirus, with more than 220 thousand dead [@nyt2020]. Reporting from a few months earlier, however, indicates that the official reports may be undercounts [@Lu2020].

Although the World Health Organization declared COVID-19 a pandemic on March 11 [@Wan2020], the response from the United States' federal government was slow. In the months to come, the Trump Administration would push responsibility to states and local governments, downplay the severity of the pandemic, and argue against the widespread stay-at-home orders promoted by public health experts [@Shear2020]. Much of the United States remained at home throughout the summer even as peer nations were able to return to more normal daily life [@Douglas2020]. The Trump Administration's response to the pandemic was consistently criticized in the press, with Time Magazine arguing that a "complete catalog of Trump's failures to adequately address the pandemic is the stuff of books, not single articles" [@Fitzpatrick2020].
 
The COVID-19 pandemic did not hit all Americans equally. A burgeoning literature is beginning to examine the racially disparate impact the virus has had on communities of color—and, in particular, Black communities. Although comprehensive data are not available in all states, an early study looked at the racial breakdown in hospitalizations in 12 states between April 30 and June 24, 2020 [@Karaca-Mandic2021]. In each of the 12 states, whites made up a far lower share of the hospitalized population than the statewide residential population, while "the percentage of hospitalizations among Black patients exceeded the percentage of their representative proportion of the state population in all 12 states" [@Karaca-Mandic2021, 133]. Similarly, a report from the Centers for Disease Control and Prevention found evidence of highly racially disparate hospitalization rates early in the pandemic [@Garg2020]. These trends continued into the spring of 2021—as of April 23rd that year, Black and Latino Americans had died from COVID-19 at roughly twice the rate of white Americans; this figure was even higher for Native Americans [@cdc2021]. Scholars are already identifying the ways in which systemic racism---and not "inherent" or "biological" racial differences---have led to these discrepancies [@Johnson-Agbakwu2020; @Egede2020].

Our understanding of the electoral effects of threatening policy has grown in recent years, with scholars arguing that discriminatory governmental (in)action can lead to higher voter turnout among impacted communities [@HoSang2010]. The COVID-19 pandemic presents a unique opportunity to extend our understanding of the mechanisms of this "political threat," particularly as it applies to racial and ethnic minorities. When citizens feel that they are being targeted by their government because of their racial or ethnic identity, such targeting can lead to greater political knowledge, higher likelihood of attending protests, and increased propensity to cast a ballot. Sometimes framed as backlash against a racially discriminatory government, it seems that—under certain circumstances—racial minorities understand the political sphere as a site for contesting this aggressive state action.

At the same time, many of these "political threats" that have spurred increased turnout among minorities are also linked with *demobilizing* effects in other work. The effects of political efficacy on political participation have been studied extensively over the past half-century: it is fairly well settled that higher external efficacy---that is, a belief in the "responsiveness of governmental authorities and institutions to citizens' demands" [@Niemi1991, 1408]---is associated with higher levels of participation [@Tarrow1998]. Government action that undermines citizens' belief in the responsiveness of the state, then, is likely to be demobilizing. Experiencing a discriminatory state could lower external efficacy and lead to a withdrawal from the political system. To be sure, the demobilizing potential of discriminatory action are not limited to efficacy mechanisms. Policies undermining individ- uals' ability to access government services, for instance, could place burdens on households, thus raising the opportunity cost of voting and decreasing turnout.

@Nichols2020a draws attention to this discrepancy in the literature, asking scholars to think more explicitly about how policy threat transforms a potentially demobilizing context into a mobilizing one. This project uses the COVID-19 pandemic to do just that. The potential "treatments" from the pandemic are clear: on the one hand, the death of a loved one can cause voters to withdraw from the political process [e.g. @Hobbs2014]. On the other hand, the racially disparate nature of the pandemic may have led voters to feel targeted because of their racial or ethnic identity. Using individual-level death records from the state of Washington, I decompose these two effects: by leveraging a triple-differences model, I estimate the separate turnout effects of living with someone who died
from something other than COVID-19 and of living with someone who died from COVID-19, relative to voters who lived with no one who died. I expect that turnout was higher for minority voters whose housemates died from COVID-19, and that this difference captures the political threat response. Importantly, such a set-up allows me to identify a mobilizing effect from COVID-19 even if the overall treatment effect is negative. Put differently: if turnout was higher for voters whose housemates died from COVID than voters whose housemates died from another cause, I can identify a mobilizing effect from COVID---even if their actual turnout remains below that of voters who lived with no one who died.

At the same time, the administrative data cannot give us insight into the psychological mechanisms at play. I argue that a sense of linked fate---that is, the sense that one's own life is shaped in no small part by one's racial identity [@Dawson1995]---should activate mobilization in the face of a political threat. Using data from the 2020 Cooperative Election Study (CES) I show that contact with COVID-19 increased turnout for minorities with high levels of linked fate, but that contact with the virus was demobilizing for voters with low levels of linked fate.

# Literature and Theory {-}

## Policy Threat {-}

When citizens link negative life circumstances to government action, such circumstances can lead to higher political involvement. @Piven1979 and @Schlozman1979, for instance, document how workers become politically engaged when they understand their unemployment as a widespread phenomenon that demands collective government response and not an individual failure. Similarly, @Campbell2003a documents a surge in political letter writing among senior citizens in response to threats to Social Security and Medicare. There is some indication that the mobilization of a policy threat is particularly pronounced among voters with high personal efficacy [@Rudolph2000].

Nowhere is the mobilizing potential of threatening policy clearer than when it comes to issues impacting racial and ethnic minorities. Much of this body of research can be traced back to proposed changes in California's policy toward Latino immigrants in the 1990s, when anti-immigrant proposals spurred Latin Americans to take political action [@HoSang2010]. Scholars have increasingly used the framework of threat and electoral self-preservation to understand the political behavior of Latinos in many domains: @Zepeda-Millan2017, for instance, shows that threats at the federal level led to widespread participation in mass protests, while @White2016 argues that increased county-level immigration enforcement increases Latino turnout. These threats can take many forms: @White2016 analyzes the impact of racist immigration policy, while @Perez2015 explores the impact of xenophobic rhetoric. Importantly, these analyses are not limited to the mobilization of Latinos. @Towler2018 finds that Black Americans with angrier feelings toward Donald Trump were more likely to vote; they argue that this anger had its genesis in the threat Trump posed to Black America. @TamCho2006a shows that Arab-Americans can also be prompted to political action by what they call "worrisome government policy action"---and that this effect is largest among individuals with greatest access to political information. They sum up: "A solid body of evidence… indicates that political mobilization is a direct response to the degree of threat and discrimination a group experiences" [@TamCho2006a, 978].

@TamCho2006a is correct that much literature has established that actively threatening moves by the government can prompt large-scale responses, it is less clear whether government inaction with racially disparate effects can elicit the same response. In the aftermath of a global pandemic, as climate change threatens the nation, and with a deteriorating social safety net, the largest threats to American racial minorities in the years to come might follow less from *bad* action than *in*action. Understanding whether the
government's failure to adequately respond to a disaster that disproportionately impacted nonwhite Americans prompted racial minorities to take action is of key importance.

At the same time, I take the critique of this literature made by @Nichols2020a seriously. They argue: "the straightforward notion that racialized threat mobilizes Latinxs is weakened by the literature's tendency to overpredict political mobilization, overlook individual responses to threat, and disregard the role of mobilization structures" (page 690). Specifically, they encourage scholars to "account for both mobilization and demobilization as well as for the mechanisms that enable political actors to transform the latter into the former" (page 690). To that end, I explicitly theorize and test the dual treatments involved in experiencing a tragedy for which the government is responsible.

## Opportunity Cost {-}

I begin by considering the expected effect of the death of a household member in the context of the opportunity cost literature. Although there is little existing literature relating the exogenous shock of the death of a loved one to political participation [but see @Hobbs2014], political scientists have long noted that Americans vote at lower rates when faced with competing demands on their time. After exploring the impact of economic adversity on turnout, Rosenstone [-@Rosenstone1982, 42, emphasis added] argues that "theories of political participation must take into account not only the costs associated specifically with the act of participation but other life circumstances that also place demands on the citizen... [circumstances] such as marital problems, *family illness, death of a close friend or relative*, problems at work, or a change of residences also surely increase the opportunity costs of political participation." Caring for a sick loved one, as well as funereal costs, impose large financial burdens on households [e.g. @Fan2004]. @Wyatt1999 studied caregivers after the person for whom they were caring died, finding that these caregivers spent an average of 10.8 hours per day on direct care.

@Hobbs2014 is unique in its investigation of the direct, short-term effects of the death of a spouse on voter turnout. They link records from the Social Security Master Death File to the California registered voter file to identify voters whose spouses had died in the months before and after the California Special Statewide 2009, Gubernatorial Primary 2010, and Gubernatorial General 2010 elections. Unsurprisingly, they find that voters whose spouses die immediately before or after an election are substantially less likely to vote than their matches controls, whose spouses did not die.
 
Although little research has taken up Rosenstone's charge to explore the effects of family illness or death on voter turnout, the research on other types of household shocks is perhaps illustrative. There is a large body of literature indicating that economic shocks, such as the loss of a job, cause lower turnout, especially when these shocks are not linked to wider social circumstances [@Emmenegger2015; @Marx2016; @Margalit2019). @Hassell2017 argues that voters without a strong history of participation disengage from political life when faced with stressful situations, though individuals with a robust history of engagement are unaffected. Negative health events are also linked with lower turnout [@Pacheco2015]; so too is divorce [@Sandell2005]. Each of these stressful life events demand a great deal of time, financial resources, and energy---resources that cannot then be used to register to vote, to learn about candidates, or to locate one's polling place.

## From Demobilizing to Mobilizing {-}

The household shocks studied in the literature in the previous section differ in a crucial way from the study at hand: these shocks were generally not explicitly connected to government policy and may thus have not been politicizing. @Walker2020 offers key insight into how a traditionally demobilizing experience can instead become a force for political mobilization. She examines the effects of contact with the criminal legal system on political participation, interactions historically understood as reducing participation at all levels [see, for instance, @Weaver2010; @Lerman2014]. Walker finds, however, that the demobilizing effect of contact with the criminal legal system is moderated by how an individual locates their experience in the context of national policy. She introduces the injustice framework, arguing that when individuals believe that their criminal legal involvement arises from unjust systemic forces, they can be mobilized to undertake political actions.

The steady drumbeat of reporting on the Trump Administration's failures to respond adequately to the pandemic likely made this narrative of injustice easily accessible to voters. "The Deaths of 150,000 Americans Are on Trump's Hands," read a headline in *The Nation* [@Mystal2020]. David Frum at *The Atlantic* called the pandemic "Trump's Plague" [@Frum2020] and *Slate* ran an article titled "How Trump Killed Tens of Thousands of Americans" [@Saletan2020]. "Can We Call Trump a Killer?" asked @Blow2020 in the headline of a column at *The New York Times*. Importantly, the severe racial disparities in deaths arising from COVID-19 also received widespread coverage in both mainstream outlets and ones focusing on African Americans in particular [e.g. @Kolata2020; @Robinson2020; @Blount2020]. Insofar as the narrative of the federal government's responsibility for the devastation of the pandemic and its racially disparate effects were readily accessible to nonwhite Americans, it may have activated the mobilizing sense of injustice.

Past work also indicates that group-level appeals are more effective for voters with strong attachments to the targeted identity. Recent work has demonstrated that this is especially clear among Latino Americans. "Identity appeals can have powerful effects on turnout," argues Valenzuela and Michelson [-@Valenzuela2016, 615, emphasis added], "but *only when they target politicized identities to which individuals hold strong prior attachments.*" Gutierrez et al. [-Gutierrez2019, 973] comes to a similar conclusion, arguing that "Latinos who share an immigrant-linked fate and those who felt that Latinos are racialized were more likely to feel angry during the 2016 election." It seems, then, that potentially demobilizing conditions (that is, a major party candidate undermining one's claims to citizenship and incorporation in the body politic) becomes mobilizing via a sense of linked fate.

The injustice narrative thus provides one avenue through which COVID-19 might be especially mobilizing for racial and ethnic minorities; a sense of linked fate provides another. These potentially mobilizing effects occur in tandem with the potentially demobilizing effects associated with the death of a loved one. Following the guidance of @Nichols2020a, this study seeks to decompose the opposing effects of COVID-19 to better understand their relative importance in the context of the COVID-19 pandemic.

# Research Design and Data {-}

Registered voters who lived with household members who died from COVID-19 received, in effect, two treatments. On the one hand, they faced an extreme upheaval in the death of a household member. As discussed above, there is evidence suggesting that such household-level shocks can reduce turnout. At the same time, however, these individuals were also deeply exposed to what many consider a massive policy failure—the government's response to the pandemic. The political threat literature indicates that such exposure could be mobilizing.

## Double-Matched Triple-Differences {-}

The primary data used for the initial section of this manuscript are administrative records from the State of Washington. I begin by identifying all individuals who died between January 1 and November 3, 2020.^[See https://www.doh.wa.gov/DataandStatisticalReports/HealthStatistics/Death.] These records include a variety of data about the deceased individual, including residential address and cause of death.

I then identify all registered voters who lived with someone who died during this period. The geocoded registered voter file comes from L2 Political, and includes a variety of characteristics such as age, party affiliation, gender, turnout history, as well as estimates of voters' race and ethnicity. The validity of the racial characteristics in the L2 data are an important concern given this study's emphasis on racially-contingent treatment effects. L2 uses voters' first, middle, and last names, as well as their Census block demographics, to assign their predicted race. This approach is commonly used by political scientists to infer voters' race in the registered voter file [@Imai2016]. While it likely leads to some inaccuracies at the individual-level, I assume that these errors lessen in importance when leveraging the full set of registered voters, and that any errors are effectively random and uncorrelated with exposure to COVID-19.
 
I merge the death records to the registered voter file using recorded address. DISCUSS CLEANING PROCESS ONCE I HAVE THE DATA.

I compare the turnout of individuals whose housemates had died from COVID-19 to housemates of voters who died for other reasons, and to the turnout of individuals who did not live with someone who died---a difference-in-difference-in-differences, or triple-differences, approach. There are real reasons to suspect that these three groups varied in important ways. I expect that older voters are more likely to live with an individual who died during the time period, for instance, and we know that more racial minorities died from COVID-19. One way to control for group-level differences is to use a variety of covariates in a traditional difference-in-differences framework, though that runs the risk of violating the parallel trends assumption. Here, I adopt a different approach: prior to implementing the difference-in-differences model I match voters using a genetic matching algorithm [@Sekhon2011], thereby ensuring that our treatment and control groups are substantially similar prior to the testing for treatment effects. For a fuller discussion of how matching can improve inference in difference-in-differences designs, see @Imai2020.

In the case of the study at hand, I specifically use what I call a double-matched triple-differences framework. I begin by matching each treated voter (a registered voter who lived with someone who died from COVID-19) to a primary control voter (a registered voter who lived with someone who died from something other than COVID-19). I assume that the opportunity-cost effect of living with a loved one who died was the same for both groups. By testing for a turnout difference between these groups, I therefore measure the political threat effects unique to COVID-19.

This simple set-up does not allow us to test the *overall* (or net) effect of proximal contact with COVID-19. To find the net effect, I must also compare treated voters with voters who lived with no one who died (secondary control voters). Treated voters and primary control voters are each matched to a secondary control voter using the same characteristics as the initial match. I thus construct groups of four voters: the treated voter; the primary control voter; and two secondary control voters. Any difference between the primary control and secondary control voters' turnout will measure the opportunity cost effect of living with an individual who died. Any difference between the treated and primary control voters measures the political threat mobilization associated with deaths arising from COVID-19.

After constructing the treatment, primary control, and secondary control groups, I implement a difference-in-differences-in-differences model at the individual-level, incorporating each individual's turnout history. These are estimated using an ordinary least squares regression. Robust standard errors are clustered at the level of the match [@Abadie2020]. This model estimates the following equation:

\begin{gather}
\label{eq:1}
v_{it} = \beta_0 + \beta_1Housemate Died_{i}+\beta_22020_{t} + \beta_3Housemate Died_{i}\times 2020_{t} \nonumber \\
\beta_4Housemate Died from COVID_{i} + \beta_5Housemate Died from COVID_{i}\times 2020_{t} + \\
\delta{Y}_{i} + \delta{Z}_{i} + \mathcal{E}_{it}. \nonumber
\end{gather}

Individual *i*'s turnout (*v*) in year *t* is a function of the year and whether or how their housemate died. In the equation, *$\beta$~1~Housemate Died~i~* measures the historical difference between voters whose housemates died in 2020 and voters for whom this did not happen. *$\beta$~2~2020~t~* measures the statewide change in turnout in 2020 from the baseline, while *$\beta$~3~Housemate Died~i~ × 2020~t~* tests whether 2020 turnout changed differently for voters whose housemate died in 2020 than for those who lived with no one who died. *$\beta$~3~Housemate Died~i~ × 2020~t~*, therefore, the estimated effect of living with someone who died, but not with someone who died from COVID. *$\beta$~4~Housemate Died from COVID~i~* measures the historical difference between treated and primary control voters, and *$\beta$~5~Housemate Died from COVID~i~ × 2020~t~* tests whether the causal effect of living with someone who died was different for treated voters than for their primary controls. This, then, is the estimated effect of proximity to a COVID death after accounting for any demobilizing effect of a death in general. The matrix *$\delta$Y~i~* is included in some models, and interacts voters' race / ethnicity with the aforementioned variables to investigate whether there are race-specific treatment effects. The matrix *$\delta$Z~i~* includes the covariates used in the matching procedure, included in some of the models.

This model allows me to test my first set of hypotheses:

*H1:* Turnout for voters who lived with an individual who died from a non-COVID cause turned out at lower rates than voters who lived with no one who died.

*H2:* Turnout for voters who lived with someone who died from COVID turned out at higher rates than voters who lived with individuals who died from other causes. Because of the availability of the racial injustice narrative, this was especially true for non-white voters who lived with someone who died from COVID.

Additionally, the data from the Department of Health allows me to test the timing of a house- hold death. Accordingly, I also investigate whether a household death occurring shortly be- fore the election structured turnout differently than deaths occurring earlier in the pandemic. I expect that deaths closer to the election will impose substantially higher opportunity costs, thus lowering turnout more. At the same time, the salience of the political nature of a death from COVID might be stronger shortly before the election. Formally put:

*H3:* The *negative* treatment effect of living with someone who died from a non-COVID cause was larger if the death occurred shortly before or after the election. The *positive* treatment effect of living with someone who died from COVID (relative to voters who lived
with individuals who died from other causes) was also larger if the death occurred near the election.
 
## National Survey Data {-}

The use of the individual-level records from Washington State gives us precise insight into the behavior of individuals who lived with residents who died from COVID. The use of administrative data sidesteps many of the issues associated with survey data such as small sample sizes or social desirability biases [e.g. @Sciarini2016]. These administrative data, however, have some drawbacks. They are only available in Washington State, for instance. Furthermore, they do not allow us to test how individual attitudes and dispositions shape voters' decision to participate.

To get a fuller picture of how COVID-19 may have shaped voters' sense of threat and turnout, I turn to national survey data. I make use of the Cooperative Election Study (CES, formerly known at the Congressional Cooperative Election Study). The CES has been widely used in recent years in political science, thanks in part to its massive sample size. In 2020, 61,000 individuals were included in the survey. It is weighted to be representative of American adults, and asks a variety of questions about political engagement and personal identities.

The CES asks respondents whether they or a family member were diagnosed with COVID, or whether a family member died from the disease. I test the impact of both types of contact. The CES does not ask explicitly about linked fate, but it does pose nonwhite respondents a series of 5 statements about race in the United States (such as, *Whites do not go to great lengths to understand the problems African Americans face*) and asks respondents how strongly they agree with them. These statements can be found in the Supplementary Information. For each of the 5 questions I recode answers so that they fall along a spectrum, where low answers indicate the respondent does not think race and racism are problems, and high answers indicate that respondents think race is a major issue. I use these questions to create a "racial affinity" scale ($\alpha$ = 0.7; Eigen 1: 3.47; Eigen 2: 0.58).
 
The CES is used to corroborate what I find at the individual-level in the first section and to test the impact of linked fate. Specifically, I test hypotheses 4 and 5:

*H4:* Respondents who knew someone who was diagnosed with or died from COVID-19 reported voting at higher rates. This was especially true for non-White respondents.

*H5:* Among nonwhite respondents, COVID-19 contact was especially linked with higher turnout for respondents with high levels of linked fate. COVID-19 was less associated with turnout for nonwhite respondents with low levels of linked fate.

# Results {-}

TKTKTKTKTK

Summary stats: What voters lived with people who died? Were racial minorities more likely to live with someone who died from COVID?

Balance tables: Do primary controls (people who lived with folks who died from non-COVID causes) look like the treated voters (those who lived with people who died from COVID)? Do people who lived with someone who died look like voters who lived with no one who died?

Plot the data: Left hand side raw turnout for all 3 groups;  right hand side shows turnout  for the treated, selected primary and secondary controls

Estimate the models, regression table(s)

Plot the treatment effects by time in weekly / monthly buckets

Quick discussion


## National Survey Data {-}

In the section that follows, I explore the relationship between COVID exposure, race, racial sentiment, and turnout using national survey data. The explanatory power of these models departs in important ways from the prior section: because of the cross-sectional nature of the survey data, my ability to make causal claims is limited. These limitations, however, are made up for by the national scope of the data, and the insight into personal disposition and belief that administrative data are unable to provide. When joined with the results from the previous section, we gain deep insight into both *how* COVID-19 structured (racial) turnout, and also *why* it did so.

I begin by exploring the relationship between COVID exposure and voter turnout in the 2020 CES data. I am, first of all, interested in whether COVID exposure was associated with turnout, and whether that association was different for white and non-white respondents. To estimate these relationships, I regress 2020 turnout on COVID exposure and other standard covariates (age, party, income, gender, 7-point ideological score, education, race, and 2016 turnout) using OLS. COVID exposure is also interacted with a dummy indicating whether the respondent was white, to test for minority-specific responses. Roughly 31% of respondents are not white. Just over 1 in 5 white respondents reported that they or a family member were diagnosed with COVID, and 3.3% reported a familial death from the virus. These figures for nonwhite respondents were 27% and 8%, respectively.

In Figure \ref{fig:mef-ces-1} I ask whether contact with COVID was related to turnout for white and nonwhite voters in the CES (The full regression table can be found in the Supplementary Information). Because the CES asks respondents about death and diagnosis, I test both "treatments." The results are somewhat surprising: while the "weak" treatment is perhaps associated with a small increase in turnout for white respondents (p = 0.051), it is associated with a turnout drop of roughly 1.15 percentage points for nonwhite  respondents  (p = 0.014).   As  shown  in  the  Supplementary  Information,  these results do not change using a logistic model. The strong treatment—knowing someone who died from the virus—is not statistically significantly associated with different turnout rates for white or nonwhite respondents in an OLS model, though a logistic model indicates that such contact had no effect on nonwhite turnout but was mobilizing for whites. The CES  data thus [fail to] confirm what the individual-level effect of COVID-19 contact on turnout. Of course, because the CES does not ask respondents whether they lived with someone who died from non-COVID causes, these data do not allow us to distinguish the mobilizing and demobilizing effects of COVID-19 contact on turnout


\newpage
## References {-}